name: Deploy PlatformIO package

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Upstream ref
        required: false
        default: ''
      version:
        description: Package version
        required: false
        default: ''

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy PlatformIO package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Ameba-AIoT/ameba-rtos-d
          ref: ${{ inputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version number
        id: version
        run: |
          echo "version=$(date -d "$(git log -1 --format=%cs)" +v%Y.%m.%d)" >> $GITHUB_OUTPUT

      - name: Write package.json
        uses: jsdaniell/create-json@v1.2.2
        env:
          name: framework-realtek-ambd
          version: ${{ inputs.version || steps.version.outputs.version }}
          description: sdk for amebad
        with:
          name: package.json
          json: ${{ toJSON(env) }}

      - name: Cleanup repository
        run: |
          git checkout -B platformio
          rm -rf component/common/network/lwip/lwip_v2.0.2/doc/
          rm -rf component/common/network/lwip/lwip_v2.2.0/doc/
          rm -rf project/realtek_amebaD_va0_example/GCC-RELEASE/
          rm -rf doc/
          rm -rf tools/

      - name: Commit and push changes
        env:
          version: ${{ inputs.version || steps.version.outputs.version }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          # Проверяем, есть ли изменения для коммита
          if ! git diff --quiet; then
            git add -A
            git commit -m "[${{ env.version }}] Prepare PlatformIO package"

            # Создаём тег
            git tag ${{ env.version }}

            # Устанавливаем корректный URL с аутентификацией
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

            # Отправляем ветку и тег
            git push --force origin platformio
            git push origin ${{ env.version }}
          else
            echo "No changes to commit"
          fi
